name = "RiskMeasures"
uuid = "b5a8929a-7a15-4aed-937e-21e1a404cbc5"
authors = ["Marek Petrik <mpetrik@cs.unh.edu>, Gersi Doko, and others"]
version = "0.6.1"

[deps]
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
DispatchDoctor = "0.4"
Optim = "2.0"
Distributions = "0.25"
julia = "1.12"
